"""Data models for location, infrastructure, disaster info, and generated plans."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class LocationInfo(BaseModel):
    """Geographic and place context (Zippopotam: ZIP → city, state, lat/lon)."""

    query: str = ""
    zip_code: str = ""
    city: str = ""
    state: str = ""
    latitude: float | None = None
    longitude: float | None = None
    display_name: str = ""
    region: str = ""   # state alias
    country: str = ""
    raw: dict[str, Any] = Field(default_factory=dict)


class DemographicsInfo(BaseModel):
    """US Census ACS 5-Year: population and housing by ZIP."""

    zip_code: str = ""
    population: int | None = None
    housing_units: int | None = None
    people_per_household: float | None = None
    summary: str = ""
    raw: dict[str, Any] = Field(default_factory=dict)


class InfrastructureItem(BaseModel):
    """Single infrastructure asset (hospital, shelter, road segment, etc.)."""

    type: str  # e.g. hospital, shelter, road, power_station
    name: str = ""
    latitude: float | None = None
    longitude: float | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class InfrastructureInfo(BaseModel):
    """Aggregated infrastructure data for the area."""

    items: list[InfrastructureItem] = Field(default_factory=list)
    summary: str = ""
    raw: dict[str, Any] = Field(default_factory=dict)


class DisasterEvent(BaseModel):
    """Single disaster event or alert."""

    event_type: str  # e.g. earthquake, flood, wildfire, storm
    title: str = ""
    description: str = ""
    severity: str = ""
    latitude: float | None = None
    longitude: float | None = None
    start_time: str = ""
    end_time: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class WeatherForecastPeriod(BaseModel):
    """One period from NOAA hourly forecast (wind, humidity, temp)."""

    start_time: str = ""
    end_time: str = ""
    temperature_f: float | None = None
    wind_speed_mph: float | None = None
    relative_humidity: int | None = None
    short_forecast: str = ""


class DisasterInfo(BaseModel):
    """Disaster/weather alerts (NOAA) and optional hourly forecast."""

    events: list[DisasterEvent] = Field(default_factory=list)
    summary: str = ""
    weather_forecast_summary: str = ""
    weather_periods: list[WeatherForecastPeriod] = Field(default_factory=list)
    raw: dict[str, Any] = Field(default_factory=dict)


class ReactionStep(BaseModel):
    """A single step in the immediate reaction phase."""

    order: int
    action: str
    rationale: str = ""
    priority: str = "high"  # high, medium, low


class RecoveryStep(BaseModel):
    """A single step in the recovery phase."""

    order: int
    action: str
    rationale: str = ""
    timeline: str = ""  # e.g. "0-24 hours", "1-7 days"


class ReactionRecoveryPlan(BaseModel):
    """Full reaction and recovery plan generated by the agent."""

    summary: str = ""
    reaction_steps: list[ReactionStep] = Field(default_factory=list)
    recovery_steps: list[RecoveryStep] = Field(default_factory=list)
    key_contacts_or_resources: list[str] = Field(default_factory=list)
    assumptions: list[str] = Field(default_factory=list)
    raw_response: str = ""
